### ISSUE TITLE
Jenkins pipeline maven without rtMaven

### ISSUE THREAD

**Issue by rlogiacco** [jfrog/project-examples#138]
I'm having issues using the built-in `maven.tool` so I'm using `sh` to execute maven in a docker container and I have my artifact built correctly. How can I now publish it onto Artifactory ?

Here follows a simplified version of my pipeline:

```
pipeline {
  agent {
    docker {
      image 'maven:3-alpine'
      args '-v m2:/root/.m2'
    }
  }
  stages {
    stage('Build') {
      steps {
        sh 'mvn verify -DskipTests'
        archiveArtifacts(artifacts: 'target/*.war', fingerprint: true, onlyIfSuccessful: true)
      }
    }
    stage('Test') {
      post {
        always {
          junit 'target/surefire-reports/**/*.xml'
        }
      }
      steps {
        sh 'mvn test'
      }
    }
    stage('Release') {
      when {
        expression {
          env.BRANCH_NAME == 'master'
        }
      }
      steps {
        script {
          ??????
        }
      }
    }
  }
}
```

Any example I've found uses rtMaven for building the artifact....

**Comment by eyalbe4** [comment]
@rlogiacco,
You don't have use the built in maven tool and still use the standard Artifactory pipeline APIs.
Look for the following text:
*"Instead of using rtMaven.tool, you can set the path to the Maven installation directory using the MAVEN_HOME environment variable..."* in [this](https://www.jfrog.com/confluence/display/RTF/Working+With+Pipeline+Jobs+in+Jenkins) user guide.
