### ISSUE TITLE
Cannot capture env vars for buildInfo after creating new buildInfo from docker push

### ISSUE THREAD

**Issue by kerrhome** [jfrog/project-examples#140]
Snippet from my Jenkinsfile:

```
....
// Push to docker Artifactory
def my_image = docker.build("${root_image}:${version}", "./${product_directory}")
def buildInfo = rtDocker.push("${root_image}:${version}", 'docker-local')
buildInfo.number = version
buildInfo.env.capture = true
// Publish the build info
server.publishBuildInfo(buildInfo)
```

Build is published as are the artifacts, but the build has no environment listed under the Environment tab for the Artifactory build page.

Also, there is rtDocker.addProperty, but is there a replaceProperty method?  Is there a list of all methods available?  Is there an API available for Artifactory for Jenkins?

**Comment by barbelity** [comment]
@kerrhome,

In order to collect environment variables, please replace your line: `buildInfo.env.capture = true`, with: `buildInfo.env.collect()`. The variables will be collected as this line is executed, and later be published to Artifactory.

There is currently no such method as 'replacePropery' for docker builds, through the pipeline script. As a workaround, I would suggest using our jfrog-cli for setting/deleting properties for published artifacts. Please look at the [cli documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-SettingPropertiesonFiles).

The available commands are listed in the [Working With Pipeline Jobs in Jenkins](https://www.jfrog.com/confluence/display/RTF/Working+With+Pipeline+Jobs+in+Jenkins#WorkingWithPipelineJobsinJenkins-DockerBuildswithArtifactory) page.
If you are willing to dive into code, you can check our [sources](https://github.com/jfrog/jenkins-artifactory-plugin/blob/master/src/main/java/org/jfrog/hudson/pipeline/types/Docker.java) - the @Whitelisted methods are useable from the pipeline script.

For best answer, please elaborate last question:

> Is there an API available for Artifactory for Jenkins?

I hope that I managed to clear some things up, keep me posted of further issues I can help with.

**Comment by kerrhome** [comment]
Thanks @barbelity.  I appreciate your response and I've already implemented your suggestion for collect().

As far as my last question that you brought up, I was wondering if there was something comprehensive that lists all of the methods and variables available to me from Artifactory in the Jenkins pipeline groovy code.  For instance, I know Artifactory provides Artifactory.newBuildInfo(), but what else does it provide?  I really was hoping there would be more detail about inputs, returns, methods etc available to me provided by the Jenkins Artifactory plugin.  Maybe I'm just missing it, but I only see examples around, but nothing comprehensive.  Jenkins has this: https://javadoc.jenkins.io.  Is there some equivalent for Artifactory/JFrog?

Side note: I understand the jfrog-cli and I've implemented that in our docker images, so we have access to it. My new question is, if my build starts out in the pipeline and I setup buildInfo, my_image, server etc in the pipeline, how does the bash command line know anything about those for use with the jfrog-cli?  This has been a problem for me.  I want to use both the Artifactory pipeline commands and the jfrog-cli, but as far as I can tell, they don't work with each other.

For instance, let's say I setup the build in the pipeline: 
```
def server = Artifactory.server 'Exacq'
def buildInfo = Artifactory.newBuildInfo()
```
Then I build using ```jfrog-cli npmi``` on the bash command line to build my artifact(s).  I'm able to use the cli to gather env info, dependent npm modules, etc.  Then I publish all of that using the jfrog-cli, but I want my pipeline build to reflect the built artifacts.  How do I exit the bash section where I ran the jfrog-cli commands and then have the pipeline know about anything that happened there, so the build will have a link to the build and linked artifacts?

**Comment by kerrhome** [comment]
btw, the @Whitelisted methods are a big help.  Thank you.

**Comment by barbelity** [comment]
@kerrhome I am glad to hear that we could solve the docker issue.

The most comprehensive document containing all you need to know about pipeline jobs with Artifactory, is our documentation - [Working With Pipeline Jobs in Jenkins](https://www.jfrog.com/confluence/display/RTF/Working+With+Pipeline+Jobs+in+Jenkins#WorkingWithPipelineJobsinJenkins). All available methods and executions are listed there, as we keep updating it with examples for new options when required.

Passing the generated build-info from the cli to the 'buildInfo' object in your example, is not possible. Regardless, operations you perform with the cli will appear in the build logs - including the link to the published build-info.

Appending build-infos from the pipeline script is only available for objects created using the 'Artifactory.newBuildInfo()' method.
`buildInfo1.append buildInfo2`

 Unfortunately, the Jenkins Artifactory Plugin does not include npm project building with build-info.

Another solution may be using the JFrog-cli both for building, and later publishing the build-info. There, if you specify the same 'build-name' and 'build-number' for several executions, the cli combines the generated build-infos into one.

**Comment by eyalbe4** [comment]
@kerrhome,
Please let us know if you need further assistance.
